"""Deterministic Non-Zero workflow contracts and policy."""

from aioa_cloudops_agent.domain.enums import AuthorityGate

from .authority import authority_for_capability, require_capability_authority
from .contracts import (
    ActionProposal,
    ActionResult,
    ActionTarget,
    Approval,
    AuditEvent,
    BudgetCounters,
    Checkpoint,
    ExpectedPrecondition,
    IdempotencyRecord,
    Run,
    transition_run,
)
from .enums import (
    TERMINAL_WORKFLOW_STATES,
    ActionOutcome,
    ApprovalDecision,
    AuditEventType,
    Capability,
    FailureKind,
    IdempotencyStatus,
    ObservedInstanceState,
    ProposalState,
    RecoveryDisposition,
    ResultStatus,
    WorkflowState,
)
from .errors import (
    CapabilityDeniedError,
    ControlResult,
    DurablePrerequisiteError,
    FailureDetail,
    NonZeroContractError,
    StorageConflictError,
    StorageDependencyError,
    WorkflowTransitionError,
)
from .identifiers import (
    Ec2InstanceId,
    IdempotencyKey,
    NonEmptyText,
    Sha256Digest,
    ShortIdentifier,
    Uuid7Identifier,
    generate_event_id,
    generate_proposal_id,
    generate_run_id,
    generate_trace_id,
)
from .transitions import ALLOWED_WORKFLOW_TRANSITIONS, validate_workflow_transition

__all__ = [
    "ALLOWED_WORKFLOW_TRANSITIONS",
    "TERMINAL_WORKFLOW_STATES",
    "ActionOutcome",
    "ActionProposal",
    "ActionResult",
    "ActionTarget",
    "Approval",
    "ApprovalDecision",
    "AuditEvent",
    "AuditEventType",
    "AuthorityGate",
    "BudgetCounters",
    "Capability",
    "CapabilityDeniedError",
    "Checkpoint",
    "ControlResult",
    "DurablePrerequisiteError",
    "Ec2InstanceId",
    "ExpectedPrecondition",
    "FailureDetail",
    "FailureKind",
    "IdempotencyKey",
    "IdempotencyRecord",
    "IdempotencyStatus",
    "NonEmptyText",
    "NonZeroContractError",
    "ObservedInstanceState",
    "ProposalState",
    "RecoveryDisposition",
    "ResultStatus",
    "Run",
    "Sha256Digest",
    "ShortIdentifier",
    "StorageConflictError",
    "StorageDependencyError",
    "Uuid7Identifier",
    "WorkflowState",
    "WorkflowTransitionError",
    "authority_for_capability",
    "generate_event_id",
    "generate_proposal_id",
    "generate_run_id",
    "generate_trace_id",
    "require_capability_authority",
    "transition_run",
    "validate_workflow_transition",
]
